# Generated by Django 5.2.4 on 2025-08-13 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('practice_area', models.CharField(choices=[('criminal-defense', 'Criminal Defense'), ('family-law', 'Family Law'), ('personal-injury', 'Personal Injury'), ('corporate-law', 'Corporate Law'), ('immigration', 'Immigration'), ('real-estate', 'Real Estate'), ('wills-estates', 'Wills & Estates'), ('other', 'Other')], max_length=50)),
                ('preferred_contact', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('text', 'Text Message'), ('any', 'Any Method')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_responded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
